package main

import (
	"github.com/appwrite/mcp-server/config"
	"github.com/appwrite/mcp-server/models"
	tools_storage "github.com/appwrite/mcp-server/tools/storage"
	tools_health "github.com/appwrite/mcp-server/tools/health"
	tools_locale "github.com/appwrite/mcp-server/tools/locale"
	tools_users "github.com/appwrite/mcp-server/tools/users"
	tools_functions "github.com/appwrite/mcp-server/tools/functions"
	tools_account "github.com/appwrite/mcp-server/tools/account"
	tools_avatars "github.com/appwrite/mcp-server/tools/avatars"
	tools_database "github.com/appwrite/mcp-server/tools/database"
	tools_teams "github.com/appwrite/mcp-server/tools/teams"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_storage.CreateStoragelistfilesTool(cfg),
		tools_health.CreateHealthgetqueuecertificatesTool(cfg),
		tools_locale.CreateLocalegetcontinentsTool(cfg),
		tools_users.CreateUsersdeletesessionTool(cfg),
		tools_health.CreateHealthgetTool(cfg),
		tools_functions.CreateFunctionslisttagsTool(cfg),
		tools_health.CreateHealthgetstoragelocalTool(cfg),
		tools_account.CreateAccountgetlogsTool(cfg),
		tools_locale.CreateLocalegetcountriesTool(cfg),
		tools_avatars.CreateAvatarsgetimageTool(cfg),
		tools_avatars.CreateAvatarsgetcreditcardTool(cfg),
		tools_account.CreateAccountcreaterecoveryTool(cfg),
		tools_account.CreateAccountupdaterecoveryTool(cfg),
		tools_database.CreateDatabaselistcollectionsTool(cfg),
		tools_database.CreateDatabasecreatecollectionTool(cfg),
		tools_teams.CreateTeamsupdatemembershipstatusTool(cfg),
		tools_avatars.CreateAvatarsgetfaviconTool(cfg),
		tools_teams.CreateTeamsdeleteTool(cfg),
		tools_teams.CreateTeamsgetTool(cfg),
		tools_teams.CreateTeamsupdateTool(cfg),
		tools_account.CreateAccountupdatenameTool(cfg),
		tools_users.CreateUsersupdatestatusTool(cfg),
		tools_teams.CreateTeamsgetmembershipsTool(cfg),
		tools_teams.CreateTeamscreatemembershipTool(cfg),
		tools_avatars.CreateAvatarsgetflagTool(cfg),
		tools_locale.CreateLocalegetTool(cfg),
		tools_health.CreateHealthgetcacheTool(cfg),
		tools_users.CreateUsersgetlogsTool(cfg),
		tools_health.CreateHealthgetqueuewebhooksTool(cfg),
		tools_teams.CreateTeamslistTool(cfg),
		tools_teams.CreateTeamscreateTool(cfg),
		tools_health.CreateHealthgetqueueusageTool(cfg),
		tools_users.CreateUsersupdateverificationTool(cfg),
		tools_locale.CreateLocalegetlanguagesTool(cfg),
		tools_users.CreateUsersdeletesessionsTool(cfg),
		tools_users.CreateUsersgetsessionsTool(cfg),
		tools_account.CreateAccountupdateprefsTool(cfg),
		tools_account.CreateAccountgetprefsTool(cfg),
		tools_account.CreateAccountdeleteTool(cfg),
		tools_account.CreateAccountgetTool(cfg),
		tools_locale.CreateLocalegetcountriesphonesTool(cfg),
		tools_teams.CreateTeamsdeletemembershipTool(cfg),
		tools_teams.CreateTeamsupdatemembershiprolesTool(cfg),
		tools_functions.CreateFunctionscreateTool(cfg),
		tools_functions.CreateFunctionslistTool(cfg),
		tools_health.CreateHealthgetqueuefunctionsTool(cfg),
		tools_users.CreateUserslistTool(cfg),
		tools_users.CreateUserscreateTool(cfg),
		tools_database.CreateDatabasedeletedocumentTool(cfg),
		tools_database.CreateDatabasegetdocumentTool(cfg),
		tools_database.CreateDatabaseupdatedocumentTool(cfg),
		tools_users.CreateUsersdeleteTool(cfg),
		tools_users.CreateUsersgetTool(cfg),
		tools_storage.CreateStoragegetfilepreviewTool(cfg),
		tools_functions.CreateFunctionsdeleteTool(cfg),
		tools_functions.CreateFunctionsgetTool(cfg),
		tools_functions.CreateFunctionsupdateTool(cfg),
		tools_account.CreateAccountdeletesessionsTool(cfg),
		tools_account.CreateAccountgetsessionsTool(cfg),
		tools_avatars.CreateAvatarsgetqrTool(cfg),
		tools_avatars.CreateAvatarsgetinitialsTool(cfg),
		tools_database.CreateDatabasecreatedocumentTool(cfg),
		tools_database.CreateDatabaselistdocumentsTool(cfg),
		tools_account.CreateAccountupdateemailTool(cfg),
		tools_avatars.CreateAvatarsgetbrowserTool(cfg),
		tools_health.CreateHealthgetantivirusTool(cfg),
		tools_account.CreateAccountdeletesessionTool(cfg),
		tools_account.CreateAccountgetsessionTool(cfg),
		tools_health.CreateHealthgetqueuelogsTool(cfg),
		tools_account.CreateAccountcreateverificationTool(cfg),
		tools_account.CreateAccountupdateverificationTool(cfg),
		tools_functions.CreateFunctionsgetexecutionTool(cfg),
		tools_storage.CreateStoragegetfileTool(cfg),
		tools_storage.CreateStorageupdatefileTool(cfg),
		tools_storage.CreateStoragedeletefileTool(cfg),
		tools_health.CreateHealthgetdbTool(cfg),
		tools_database.CreateDatabasegetcollectionTool(cfg),
		tools_database.CreateDatabaseupdatecollectionTool(cfg),
		tools_database.CreateDatabasedeletecollectionTool(cfg),
		tools_functions.CreateFunctionsdeletetagTool(cfg),
		tools_functions.CreateFunctionsgettagTool(cfg),
		tools_users.CreateUsersupdateprefsTool(cfg),
		tools_users.CreateUsersgetprefsTool(cfg),
		tools_storage.CreateStoragegetfileviewTool(cfg),
		tools_storage.CreateStoragegetfiledownloadTool(cfg),
		tools_health.CreateHealthgetqueuetasksTool(cfg),
		tools_functions.CreateFunctionslistexecutionsTool(cfg),
		tools_functions.CreateFunctionscreateexecutionTool(cfg),
		tools_health.CreateHealthgettimeTool(cfg),
		tools_locale.CreateLocalegetcountrieseuTool(cfg),
		tools_locale.CreateLocalegetcurrenciesTool(cfg),
		tools_functions.CreateFunctionsupdatetagTool(cfg),
		tools_account.CreateAccountupdatepasswordTool(cfg),
	}
}
